---

- name: Metrics-Server | Checking old installation files
  stat:
    path: "{{ kubesphere_dir }}/metrics-server/auth-reader.yaml"
  ignore_errors: True
  register: metrics_server_old_check


- name: Metrics-Server | deleting old prometheus-operator
  shell: "{{ bin_dir }}/kubectl delete -f {{ kubesphere_dir }}/metrics-server/"
  register: import
  failed_when: "import.stderr and 'NotFound' not in import.stderr"
  when: metrics_server_old_check.stat.exists


- name: Metrics-Server | deleting old metrics-server files
  file:
    path: "{{ kubesphere_dir }}/{{ item }}"
    state: absent
  ignore_errors: True
  loop:
    - "metrics-server"
  when: metrics_server_old_check


- name: Metrics-Server | Getting metrics-server installation files
  copy:
    src: "metrics-server"
    dest: "{{ kubesphere_dir }}/"


- name: Metrics-Server | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/metrics-server/{{ item.file }}"
  with_items:
    - { name: values, file: values.yaml, type: config }


- name: Metrics-Server | Check Metrics-Server
  shell: >
    {{ bin_dir }}/helm list metrics-server
  register: metrics_server_check
  ignore_errors: True

- block:
    - name: Metrics-Server | Installing metrics-server
      shell: >
        {{ bin_dir }}/helm upgrade --install metrics-server {{ kubesphere_dir }}/metrics-server  --namespace kube-system
      register: result
      ignore_errors: True


    - name: Metrics-Server | Installing metrics-server retry
      shell: >
        {{ bin_dir }}/helm del --purge metrics-server &&
        sleep 5 &&
        {{ bin_dir }}/helm upgrade --install metrics-server {{ kubesphere_dir }}/metrics-server --namespace kube-system
      when:
        - result.rc != 0
  when:
    - (metrics_server_check.stdout.find("DEPLOYED") == -1) or (metrics_server_check.stdout.find("0.3.1-0217") == -1)

- name: Metrics-Server | Waitting for v1beta1.metrics.k8s.io ready
  shell: >
    {{ bin_dir }}/kubectl get apiservices v1beta1.metrics.k8s.io -o jsonpath='{.status.conditions[0].status}'
  register: metrics_health
  until: metrics_health.stdout.find("True") != -1
  retries: 60
  delay: 10