---
dbHost: kubesphere.cluster-ct8xyyymi47s.us-east-1.rds.amazonaws.com
dbPort: 3306

etcdHost: etcd.kubesphere-system.svc
etcdPort: 2379
etcdEndpoint: "{{ etcdHost }}:{{ etcdPort }}"

redisHost: redis.kubesphere-system.svc
redisPort: 6379
redisEndpoint: "{{ redisHost }}:{{ redisPort }}"
